### ISSUE TITLE
How to set a new DataSource?

### ISSUE THREAD

**Issue by Big3Software** [MdIqubal/Recyclable-Scroll-Rect#3]
Thanks for your great work!

Is there a way to set a new DataSource?

Currently, when I set a new DataSource or update items in the DataSource nothing happens.

Maybe you can add a "Reset" function?

Jus

CORRECTION:
It's seems to be only a problem when the new DataSource has fewer elements than the original one.

**Comment by MdIqubal** [comment]
Hi. Glad that you liked the work. 
Thank you for pointing that out. That is indeed an issue. There was a huge amount of refactoring of code in the last update and this part was missed.  We do need a reset function or assigning a new datasource should automatically reset the list. I will fix this issue and update the repo ASAP.

**Comment by MdIqubal** [comment]
The issue has been fixed and updated. After assigning a new data-source you can now call the ReloadData() function. Alternatively, the ReloadData(IRecyclableScrollRectDataSource dataSource) function can also be used for assigning a new data-source and reloading the data in a single line.

**Comment by Big3Software** [comment]
Cool, thanks!
